public static function districts()
    {
        return  $districts = [
        'AJK' =>
            ['Muzaffarabad',
                'Hattian Bala',
                'Neelum',
                'Mirpur',
                'Bhimber',
                'Kotli',
                'Poonch',
                'Bagh',
                'Haveli',
                'Sudhnati',
            ],

        'Balochistan' =>
            ['Awaran',
                'Barkhan',
                'Chagai',
                'Dera Bugti',
                'Gwadar',
                'Harnai',
                'Jafarabad',
                'Jhal Magsi',
                'Kachhi',
                'Kalat',
                'Kech',
                'Kharan',
                'Khuzdar',
                'Killa Abdullah',
                'Killa Saifullah',
                'Kohlu',
                'Lasbela',
                'Lehri',
                'Loralai',
                'Mastung',
                'Musakhel',
                'Nasirabad',
                'Nushki[18]',
                'Panjgur',
                'Pishin',
                'Quetta',
                'Sherani',
                'Sibi',
                'Sohbatpur',
                'Washuk',
                'Zhob',
                'Ziarat',
                'Duki',
            ],
        'Gilgit Baltistan' =>
            ['Ghanche',
                'Skardu',
                'Astore',
                'Diamer',
                'Ghizer',
                'Gilgit',
                'Hunza',
                'Kharmang',
                'Shigar',
                'Nagar',
                'Gupis–Yasin',
                'Tangir',
                'Darel',
                'Roundu',
            ],
        'KPK' =>
            ['Abbottabad',
                'Bajaur',
                'Bannu',
                'Battagram',
                'Buner',
                'Charsadda',
                'Chitral',
                'Dera Ismail Khan',
                'Hangu',
                'Haripur',
                'Karak',
                'Khyber',
                'Kohat',
                'Kurram',
                'Lakki Marwat',
                'Lower Dir',
                'Lower Kohistan',
                'Malakand',
                'Mansehra',
                'Mardan',
                'Mohmand',
                'North Waziristan',
                'Nowshera',
                'Orakzai',
                'Peshawar',
                'Shangla',
                'South Waziristan',
                'Swabi',
                'Swat',
                'Tank',
                'Torghar',
                'Upper Dir',
                'Upper Kohistan',
            ],
        'Punjab' =>
            ['Attock',
                'Bahawalnagar',
                'Bahawalpur',
                'Bhakkar',
                'Chakwal',
                'Chiniot',
                'Dera Ghazi Khan',
                'Faisalabad',
                'Gujranwala',
                'Gujrat',
                'Hafizabad',
                'Jhang',
                'Jhelum',
                'Kasur',
                'Khanewal',
                'Khushab',
                'Lahore',
                'Layyah',
                'Lodhran',
                'Mandi Bahauddin',
                'Mianwali',
                'Multan',
                'Muzaffargarh',
                'Narowal',
                'Nankana Sahib[5]',
                'Okara',
                'Pakpattan',
                'Rahim Yar Khan',
                'Rajanpur',
                'Rawalpindi',
                'Sahiwal',
                'Sargodha',
                'Sheikhupura',
                'Sialkot',
                'Toba Tek Singh',
                'Vehari',
            ],
        'Sindh' =>
            ['Badin',
                'Dadu',
                'Ghotki',
                'Hyderabad',
                'Jacobabad',
                'Jamshoro',
                'Karachi Central',
                'Karachi East',
                'Karachi South',
                'Karachi West',
                'Kashmore',
                'Khairpur',
                'Korangi',
                'Larkana',
                'Malir',
                'Matiari',
                'Mirpur Khas',
                'Naushahro Feroze',
                'Qambar Shahdadkot',
                'Sanghar',
                'Shaheed Benazir Abad',
                'Shikarpur',
                'Sujawal',
                'Sukkur',
                'Tando Allahyar',
                'Tando Muhammad Khan',
                'Tharparkar',
                'Thatta',
                'Umerkot'],
    ];
    }
